### ISSUE TITLE
Request for New Release to Include Types

### ISSUE THREAD

**Issue by MrAndriy** [kalisio/feathers-s3#18]
Hello @claustres ,

I hope this message finds you well. Could you please consider publishing a new release of the library? I’ve added new types recently, and incorporating them in an official release would significantly improve type safety and consistency for users.

Thank you very much for your support!

Best regards,
Andriy Mriy

**Comment by cnouguier** [comment]
Hi @MrAndriy 
We can plan to do the release for monday (maybe today or this week end). 
In the meantime, we'll try to update the AWS SDK.

**Comment by cnouguier** [comment]
@MrAndriy finally this is done. 
Thanks for your contribution :)
